name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Commit messages ${{ join(github.event.commits*.message, ', ') }} Should skip? ${{ contains(github.event.commits*.message, 'skip ci') }}."
