name: Release Next Version

on:
  schedule:
    - cron: '0 17 * * MON' # Every Monday at 5pm UTC
  workflow_dispatch: # Manual trigger

env:
  RUN_JOBS: ${{ github.repository == 'rwinch/gha-quickstart' }}

jobs:
  release-next-version:
    name: Initiate Release If Scheduled
    runs-on: ubuntu-latest
    steps:
      - id: check-release-due
        name: Check Release Due
        if: env.RUN_JOBS == 'true'
        run: |
          mkdir -p build/github/milestones
          echo "true" > build/github/milestones/is-due-today
          echo "::set-output name=is_due_today::$(cat build/github/milestones/is-due-today)"
      - id: check-open-issues
        name: Check Open Issues
        if: steps.check-release-due.outputs.is_due_today == 'true'
        run: |
          mkdir -p build/github/milestones
          echo "false" > build/github/milestones/is-open-issues
          echo "::set-output name=is_open_issues::$(cat build/github/milestones/is-open-issues)"
      - id: release
        name: Initiate the Release
        if: steps.check-open-issues.outputs.is_due_today
        run: echo "Releasing"
      - id: notify-result
        name: Notify the Result
        if: failure()
        run: echo "Failed"
